#!/bin/bash

sudo rm -r out

if [[ ! -d gcc ]]; then
git clone https://github.com/ruben1863/android_gcc_6.4.1_arm-eabi gcc
fi
mkdir -p out
export CROSS_COMPILE=${PWD}/gcc/bin/arm-eabi-
export USE_CCACHE=1
export ARCH=arm
export SUBARCH=arm
export TARGET=out
make O=$TARGET ARCH=$ARCH CROSS_COMPILE=$CROSS_COMPILE maya_bsp_defconfig | tee -a Defconfig.log
make O=$TARGET ARCH=$ARCH CROSS_COMPILE=$CROSS_COMPILE -j8 | tee -a Kernel.log
